### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ApiError

### ISSUE THREAD

**Issue by SpoiledMonk** [node-vk-bot-api/node-vk-bot-api#104]
День не могу разобраться. Что не так?
Скрипт: 
```
const VkBot = require('node-vk-bot-api')
var token = 'тутТокен';

const bot = new VkBot(token)

bot.on((ctx) => {
    var message = ctx.message.body;
    ctx.reply(message);
});

bot.startPolling()
```
Ответ при запуске:
```
[nodemon] starting `node index.js`
(node:10625) UnhandledPromiseRejectionWarning: Error: Request failed with status code 504
    at createError (/Users/markmoyseev/Documents/js/samp/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/markmoyseev/Documents/js/samp/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/markmoyseev/Documents/js/samp/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:10625) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10625) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ParanoikTemp** [comment]
я хз почему но отсюда лучше код не копировать.

Напиши сам по чуть чуть

**Comment by ParanoikTemp** [comment]
А нет. Я знаю. Ты наверно не настроил лонг пол в группе

**Comment by e965** [comment]
Похожая ошибка. Проблема [где-то здесь](https://github.com/node-vk-bot-api/node-vk-bot-api/blob/0cf145cb81cd1603310ed67615dad2a52e762e7e/lib/utils/execute.js#L29), очевидно.

```
(node:7508) UnhandledPromiseRejectionWarning: Error: ApiError
    at C:\bots\bot\node_modules\node-vk-bot-api\lib\utils\execute.js:33:20
    at Array.forEach (<anonymous>)
    at C:\bots\bot\node_modules\node-vk-bot-api\lib\utils\execute.js:29:34
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use 'node --trace-warnings ...' to show where the warning was created)
(node:7508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict' (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bifot** [comment]
https://github.com/node-vk-bot-api/node-vk-bot-api/blob/master/README.md#error-handling
