### ISSUE TITLE
Ошибка при попытке запуска

### ISSUE THREAD

**Issue by evgarik** [node-vk-bot-api/node-vk-bot-api#18]
`node_modules/node-vk-bot-api/lib/index.js:18
    Object.entries({ ...methods, api, callExecute }).forEach(([key, method]) => {
                     ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)`

node.js - v.8.1.2

Помогите разобраться.
Заранее благодарен.

**Comment by bifot** [comment]
Попробуй обновить Node до 8.5.
