### ISSUE TITLE
connect ETIMEDOUT 87.240.129.132:443

### ISSUE THREAD

**Issue by arpavlyutkin** [node-vk-bot-api/node-vk-bot-api#24]
Работает сначала нормально первые 5-10 минут, потом постоянно ошибка:
В чем проблема может быть? Это решил на сервер бота закинуть, локально все работало нормально.
`
Error: Error: connect ETIMEDOUT 87.240.129.132:443
    at module.exports (/root/chat-bot/bot/node_modules/node-vk-bot-api/lib/api.js:17:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by bifot** [comment]
Что это за IP-адрес?
