### ISSUE TITLE
Использование нескольких сцен

### ISSUE THREAD

**Issue by GoshanFloyd** [node-vk-bot-api/node-vk-bot-api#71]
При создании несколько объектов Scene происходит ошибка
`(node:21594) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at Stage.enter (/home/gkulik/WebstormProjects/vk-capture-bot/src/lib/stage.js:15:50)
    at Object.enter (/home/gkulik/WebstormProjects/vk-capture-bot/src/lib/stage.js:46:26)
    at bot.on (/home/gkulik/WebstormProjects/vk-capture-bot/app.js:54:23)
    at fn (/home/gkulik/WebstormProjects/vk-capture-bot/node_modules/node-vk-bot-api/lib/methods/command.js:11:18)
    at VkBot.module.exports (/home/gkulik/WebstormProjects/vk-capture-bot/node_modules/node-vk-bot-api/lib/methods/next.js:21:14)
    at VkBot.module.exports (/home/gkulik/WebstormProjects/vk-capture-bot/node_modules/node-vk-bot-api/lib/methods/next.js:24:17)
    at middleware (/home/gkulik/WebstormProjects/vk-capture-bot/node_modules/node-vk-bot-api/lib/methods/use.js:5:43)
    at /home/gkulik/WebstormProjects/vk-capture-bot/src/lib/stage.js:70:13
    at fn (/home/gkulik/WebstormProjects/vk-capture-bot/node_modules/node-vk-bot-api/lib/methods/use.js:5:16)
    at VkBot.module.exports (/home/gkulik/WebstormProjects/vk-capture-bot/node_modules/node-vk-bot-api/lib/methods/next.js:21:14)
(node:21594) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21594) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ggffggg00** [comment]
Точно такая же ошибка

**Comment by ggffggg00** [comment]
Проблема была решена здесь #23
